//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.17 at 03:59:39 PM MSK 
//


package by.epam.nikolaev.ilya.bean;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.epam.by/deviceSimpleTypes}isPeripheral"/>
 *         &lt;element ref="{http://www.epam.by/deviceSimpleTypes}energyConsumption" minOccurs="0"/>
 *         &lt;element ref="{http://www.epam.by/deviceSimpleTypes}hasCooler"/>
 *         &lt;element ref="{http://www.epam.by/devices}devicesGroup"/>
 *         &lt;element ref="{http://www.epam.by/devices}port"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "isPeripheral",
    "energyConsumption",
    "hasCooler",
    "devicesGroup",
    "port"
})
@XmlRootElement(name = "type")
public class Type {

    @XmlElement(namespace = "http://www.epam.by/deviceSimpleTypes")
    protected boolean isPeripheral;
    @XmlElement(namespace = "http://www.epam.by/deviceSimpleTypes")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger energyConsumption;
    @XmlElement(namespace = "http://www.epam.by/deviceSimpleTypes")
    protected boolean hasCooler;
    @XmlElement(required = true)
    protected String devicesGroup;
    @XmlElement(required = true)
    protected Port port;

    /**
     * Gets the value of the isPeripheral property.
     * 
     */
    public boolean isIsPeripheral() {
        return isPeripheral;
    }

    /**
     * Sets the value of the isPeripheral property.
     * 
     */
    public void setIsPeripheral(boolean value) {
        this.isPeripheral = value;
    }

    /**
     * Gets the value of the energyConsumption property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEnergyConsumption() {
        return energyConsumption;
    }

    /**
     * Sets the value of the energyConsumption property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEnergyConsumption(BigInteger value) {
        this.energyConsumption = value;
    }

    /**
     * Gets the value of the hasCooler property.
     * 
     */
    public boolean isHasCooler() {
        return hasCooler;
    }

    /**
     * Sets the value of the hasCooler property.
     * 
     */
    public void setHasCooler(boolean value) {
        this.hasCooler = value;
    }

    /**
     * Gets the value of the devicesGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDevicesGroup() {
        return devicesGroup;
    }

    /**
     * Sets the value of the devicesGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDevicesGroup(String value) {
        this.devicesGroup = value;
    }

    /**
     * Gets the value of the port property.
     * 
     * @return
     *     possible object is
     *     {@link Port }
     *     
     */
    public Port getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     * @param value
     *     allowed object is
     *     {@link Port }
     *     
     */
    public void setPort(Port value) {
        this.port = value;
    }

}
